#include <iostream.h>
#include <conio.h>
#include <time.h>

/* this implimentation is broken
void merge(int a[], int low, int mid, int high) {
    int k, nl, nr;
    nl = mid - low + 1;
    nr = r - mid;
    int larr[500], rarr[500];

    for (int i = 0; i < nl; i++)
        larr[i] = a[low + i];
    for (int j = 0; j < nr; j++)
        rarr[j] = a[mid + low + j];

    int i = 0;
    int j = 0;
    int k = 1;

    while(i < nl && j < nr) {
        if (larr[i] <= rarr[j])
            a[k] = larr[i++];
        else
            a[k] = rarr[j++];
    }

    while (i < nl)
        a[k++] = larr[i++];
    
    while (j < nr)
        a[k++] = rarr[j++];
}
*/

void merge(int a[], int low, int mid, int high) {
    int i = low, k = low;
    int j = mid + 1;
    int c[10];

    while (i <= mid && j <= high)
        if (a[i] < a[j])
            c[k++] = a[i++];
        else
            c[k++] = a[j++];

    while (i <= mid)
        c[k++] = a[i++];

    while (j <= high)
        c[k++] = a[j++];

    for (int i = low; i < k - 1; i++)
        a[i] = c[i];
}

void mergeSort(int a[], int low, int high) {
    if (low < high) {
        int mid = (low + high) / 2;
        mergeSort(a, low, mid);
        mergeSort(a, mid + 1, high);
        marge(a, low, mid, high);
    }
}

int main() {
    int n, a[20];
    clock_t start, end;
    clrscr();

    cout << "Enter the number of elements: ";
    cin >> n;

    cout << "The elements selected are:\n";
    for (int i = 0; i < n; i++) {
        a[i] = rand();
        cout << a[i] << "\t";
    }

    start = clock();
    mergeSort(a, 0, n - 1);
    end = clock();

    cout << "\nThe sorted array is:\n";
    for (int i = 0; i < n; i++)
        cout << a[i] << "\t";
    
    cout << "\nThe total time taken is: " << (end - start) / CLOCKS_PER_SEC << endl;

    getch();
}

/* OUTPUT:
Enter the number of elements: 10
The elements selected are:
 ------ 10 random numbers generated by computer
The sorted array is:
 ------ those 10 numbers in order
THe total time taken is: ----- usually 0
*/
